// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0mcR00UX1dEbxijnRrY1Jn7IQCHqE9q4',
    appId: '1:799693652825:web:3433376dc2c962aa5f0248',
    messagingSenderId: '799693652825',
    projectId: 'nsuride-23865',
    authDomain: 'nsuride-23865.firebaseapp.com',
    storageBucket: 'nsuride-23865.firebasestorage.app',
    measurementId: 'G-ZQSCX6FNSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwEwPUZvFdEzOkx7Yz2SuOyLJ--_d3oZE',
    appId: '1:799693652825:android:d945df3ab436e6795f0248',
    messagingSenderId: '799693652825',
    projectId: 'nsuride-23865',
    storageBucket: 'nsuride-23865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VdUWOQzj8s3ww_fiHnq-BW82XbCm42Q',
    appId: '1:799693652825:ios:0785786661c809685f0248',
    messagingSenderId: '799693652825',
    projectId: 'nsuride-23865',
    storageBucket: 'nsuride-23865.firebasestorage.app',
    iosBundleId: 'com.nsuride.nsurideMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VdUWOQzj8s3ww_fiHnq-BW82XbCm42Q',
    appId: '1:799693652825:ios:0785786661c809685f0248',
    messagingSenderId: '799693652825',
    projectId: 'nsuride-23865',
    storageBucket: 'nsuride-23865.firebasestorage.app',
    iosBundleId: 'com.nsuride.nsurideMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0mcR00UX1dEbxijnRrY1Jn7IQCHqE9q4',
    appId: '1:799693652825:web:d196218cd04756475f0248',
    messagingSenderId: '799693652825',
    projectId: 'nsuride-23865',
    authDomain: 'nsuride-23865.firebaseapp.com',
    storageBucket: 'nsuride-23865.firebasestorage.app',
    measurementId: 'G-M85KQTR34P',
  );
}
